AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      Role: <TODO>
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/<TODO>/'
            Method: post